In [1]:
class Meta_Search_Optimizer:
    
    '''Meta Search Optimizer
       
       @init:
       max_steps = max number of iterations
       verbose = True shows progress bar
       
       @optimize:
           *input:
               f = function to be optimized
               warning: 
                   - f.opt = optimal value
                   - f.domain = interval to search, e.g. [-5, 5]
                   - f.dimension = dimension of the function
           *output:
               (best_x, number of steps) if optimal point was found else (None, -1)
    '''
    
    def __init__(self, meta_model, init_hf_strategy="zero", best_meta_point_strategy="lowest", 
                 hf_strategy="random", nb_samples=10, size_hf=5, max_steps=100000, verbose=False):
        self.meta_model = meta_model
        self.init_hf_strategy = init_hf_strategy
        self.best_meta_point_strategy = best_meta_point_strategy
        self.hf_strategy = hf_strategy
        self.nb_samples = nb_samples
        self.size_hf = size_hf
        self.max_steps = max_steps
        self.verbose = verbose
        
    def init_hf(self):
        if self.init_hf_strategy == "zero":
            return np.array([(0,0,0)]*self.size_hf)
        
    def best_meta_point(self, meta_points, meta_evaluations, hf):
        if self.best_meta_point_strategy == "lowest":
            meta_evaluations = meta_evaluations.reshape(self.nb_samples)
            indexes = np.argsort(meta_evaluations)
            hf = np.array(hf)
            if hf.size == 0:
                return meta_points[indexes[0]]
            for idx in indexes:
                if meta_points[idx] not in hf[:, 0:2]:
                    return meta_points[idx]
            return meta_points[indexes[0]]
        if self.best_meta_point_strategy == "random":
            index = np.random.randint(0, len(meta_points))
            return meta_points[index]
        
    def optimize(self, f):
        
        #Init best values:
        best_x = [None] * f.dimension 
        best_y = 99999.0
        
        #Init history
        hf = []
        curr_hf = self.init_hf()
        
        #Define Iterator:
        if self.verbose:
            iterator = tqdm(range(self.max_steps))
        else:
            iterator = range(self.max_steps)
        
        #Iteration:
        for step in iterator:
            
            #1) Select n random points to be evaluated by meta-model
            meta_points = (f.domain[1] - f.domain[0]) * np.random.random_sample((self.nb_samples, f.dimension)) + f.domain[0]
            
            #2) Meta-evaluate points in meta-model
            meta_evaluations = self.meta_model.predict(meta_points, curr_hf)
            
            #3) Get the next point (x_t+1)
            new_x = self.best_meta_point(meta_points, meta_evaluations, hf)

            #4) Evaluate this point in function
            new_y = f(new_x)
            
            if step % 1000 == 0:
                
                print(meta_points)
                print(meta_evaluations)
                print(new_x)
                print(new_y)
                print()
            
            #Check if it is an improvement:
            if new_y < best_y: 
                best_y = new_y
                best_x = new_x
                
                #Check if it is a solution:
                if round(best_y, 2) == f.fopt:
                    return (list(best_x), step)

            #Save train data:
            #dataset.append(np.array([np.array(best_point), np.array(curr_hist), np.array(f_eval)]))

            #5) Add this info in your history
            info = (new_x[0], new_x[1], new_y)  #TODO: here it's only 2D problem!
            hf.append(info)

            #6) Select next current history
            curr_hf = self.select_hf(hf)
            
        return (None, -1)
            
    def select_hf(self, hf):

        if self.hf_strategy == "gagne":
            
            if len(hf) < self.size_hf:
                choices = np.random.choice(len(hf), self.size_hf)
                curr_pop = np.array([hf[i] for i in choices])
                return curr_pop
            else:
                #50% top:
                top50 = sorted(range(len(hf)), key=lambda i: hf[i], reverse=True)[-self.size_hf//2:]

                #50% random:
                random50 = [random.randint(0, len(hf)-1) for i in range(self.size_hf//2)]

                all_indexes = sorted(top50 + random50)
                curr_pop = [(hf[ind][0], hf[ind][1], hf[ind][2]) for ind in all_indexes]

                return np.array(curr_pop)

        elif self.hf_strategy == "random":
            hf = np.array(hf)
            idx = np.random.choice(len(hf), self.size_hf)
            return hf[idx]

In [2]:
class Random_Search_Optimizer:
    
    '''Random Search Optimizer
       
       @init:
       max_steps = max number of iterations
       verbose = True shows progress bar
       
       @optimize:
           *input:
               f = function to be optimized
               warning: 
                   - f.opt = optimal value
                   - f.domain = interval to search, e.g. [-5, 5]
                   - f.dimension = dimension of the function
           *output:
               (best_x, number of steps) if optimal point was found else (None, -1)
    '''
    
    def __init__(self, max_steps=100000, verbose=False):
        self.max_steps = max_steps
        self.verbose = verbose
    
    def optimize(self, f):
        
        #Init best values:
        best_x = [None] * f.dimension 
        best_y = 99999.0

        #Define Iterator:
        if self.verbose:
            iterator = tqdm(range(self.max_steps))
        else:
            iterator = range(self.max_steps)
        
        #Iteration:
        for step in iterator:

            #Choose random x and evaluate it:
            new_x = (f.domain[1] - f.domain[0]) * np.random.random_sample(f.dimension) + f.domain[0]
            new_y = f(new_x)

            #Check if it is an improvement:
            if new_y < best_y: 
                best_y = new_y
                best_x = new_x

                #Check if it is a solution:
                if round(best_y, 2) == f.fopt:
                    return (list(best_x), step)

        return (None, -1)

In [3]:
class Evaluator:
    
    '''Evaluator
       
       @init:
       nb_trials = max number of iterations
       verbose = True shows progress bar
       
       @optimize:
           *input:
               f = function to be optimized
               warning: 
                   - f.opt = optimal value
                   - f.domain = interval to search, e.g. [-5, 5]
                   - f.dimension = dimension of the function
                optimizer = optimize that will be used to optimize the function
           *output:
               if optimal point was found in all iterations: 
                   {"mean": mean, "stdev": stdev}
               else: 
                   {"mean": None, "stdev": None}
    '''
    
    def __init__(self, nb_trials=100, verbose=1):
        self.nb_trials = nb_trials
        self.verbose = verbose

    def evaluate(self, f, optimizer):
        
        sum_x = 0
        sum_x2 = 0
        
        #Define Iterator:
        if self.verbose:
            iterator = tqdm(range(self.nb_trials))
        else:
            iterator = range(self.nb_trials)
        
        #Iteration:
        for trial in iterator:
            bestx, step = optimizer.optimize(f)
            try:
                bestx, step = optimizer.optimize(f)
            except:
                return {"mean": None, "stdev": None}
            
            sum_x += step
            sum_x2 += step*step

        mean = sum_x / self.nb_trials
        stdev = np.sqrt((sum_x2 / self.nb_trials) - (mean * mean)) 
        
        return {"mean": mean, "stdev": stdev}

In [4]:
import numpy as np
from tqdm import tqdm

import bbobbenchmarks as bn

import nbimporter
from metamodel import *

#Define problem
f = bn.F1(1)
f.domain = [-5, 5]
f.dimension = 2

#Define evaluator
evaluator = Evaluator(nb_trials=10)

Importing Jupyter notebook from metamodel.ipynb


Using TensorFlow backend.


In [ ]:
random_search_opt = Random_Search_Optimizer()

#random_search_opt.optimize(f)
#evaluator.evaluate(f, random_search_opt)

In [ ]:
model = Model()
meta_search_opt_random = Meta_Search_Optimizer(model,best_meta_point_strategy="random")

#meta_search_opt_random.optimize(f)
#evaluator.evaluate(f, meta_search_opt_random)

In [5]:
#from keras.models import load_model
#model = load_model('metamodel.h5')
#model = Model(model)

import random
model = Model()


print(model.model.layers[2].input_shape)
meta_search_opt_highest = Meta_Search_Optimizer(model,best_meta_point_strategy="lowest",hf_strategy="gagne",verbose=True)

meta_search_opt_highest.optimize(f)
#evaluator.evaluate(f, meta_search_opt_highest)

  0%|          | 304/100000 [00:00<01:05, 1517.08it/s]

(None, 128)
[[ 0.55200814 -0.3160299 ]
 [ 2.22402152 -3.21376662]
 [ 4.14901092  0.764746  ]
 [-0.40226887 -1.62810665]
 [-3.69141971 -4.96507593]
 [-1.136193   -0.26590595]
 [-2.66690025  4.00225476]
 [ 1.74956985  4.93922901]
 [-0.01593717 -0.89854811]
 [ 1.00407474 -0.7128927 ]]
[[ 0.00137018]
 [ 0.02272679]
 [-0.04484456]
 [-0.00366687]
 [-0.00108001]
 [ 0.00657178]
 [ 0.01377867]
 [-0.10054215]
 [ 0.00023585]
 [ 0.00454964]]
[1.74956985 4.93922901]
118.88188962936746



  1%|          | 1137/100000 [00:01<01:28, 1114.75it/s]

[[-1.31127707 -0.99609205]
 [ 4.91824832  2.94322377]
 [ 1.53164325  4.35836917]
 [ 0.44063632 -3.02953753]
 [ 3.58520108  1.2064341 ]
 [-1.77779662  2.66850605]
 [-0.47035362 -1.76062128]
 [ 1.86012079  4.12057331]
 [ 1.09296291 -1.31791709]
 [-2.75143995  0.4881348 ]]
[[2.6875715]
 [2.632287 ]
 [2.5889611]
 [2.718871 ]
 [2.635746 ]
 [2.6240635]
 [2.6988587]
 [2.5938773]
 [2.6869156]
 [2.6651506]]
[1.53164325 4.35836917]
111.53253098612392



  2%|▏         | 2062/100000 [00:02<02:06, 776.19it/s] 

[[ 3.3456633   1.39527198]
 [ 4.99090621 -1.7148235 ]
 [ 2.52365725 -3.27064698]
 [-4.92171562  0.99348956]
 [ 1.11981994 -0.56055432]
 [ 2.65858482 -2.92674986]
 [-1.47785087 -0.94431705]
 [ 0.63145114 -1.60434185]
 [-4.95629425  3.33274804]
 [-2.97639673 -4.92122178]]
[[2.0882316]
 [2.1384091]
 [2.157505 ]
 [2.06957  ]
 [2.1143482]
 [2.1526046]
 [2.1132867]
 [2.1295626]
 [2.030149 ]
 [2.1730003]]
[-4.95629425  3.33274804]
126.77070457313815



  3%|▎         | 3058/100000 [00:05<02:45, 586.53it/s]

[[ 4.37735635 -3.33788838]
 [-3.69573602 -1.87922737]
 [ 2.37469148 -3.85384062]
 [ 3.67624372 -4.11174089]
 [-1.08710559 -0.40661746]
 [-0.70838783  1.28210288]
 [-0.36387213  4.08374773]
 [-1.54153833 -0.92519802]
 [-2.49044183  4.21484752]
 [ 0.04725432  4.27386362]]
[[3.1183453]
 [3.083035 ]
 [3.1171815]
 [3.125021 ]
 [3.0633616]
 [3.0445838]
 [3.0123935]
 [3.0679095]
 [2.9987211]
 [3.0116267]]
[-2.49044183  4.21484752]
115.85997277137162



  4%|▍         | 4036/100000 [00:08<03:27, 463.30it/s]

[[-2.8276958  -4.24972359]
 [ 0.58805147  1.63790166]
 [ 1.61790815 -4.77638607]
 [-4.93155771 -1.87411844]
 [-0.43079344 -0.53523109]
 [ 3.26001175  4.73921916]
 [-1.22386007 -1.41907915]
 [ 2.98990233 -2.14876447]
 [ 0.32410356  1.70543365]
 [-0.12864663  2.97695031]]
[[2.743204 ]
 [2.730865 ]
 [2.8046625]
 [2.6961665]
 [2.734894 ]
 [2.7109323]
 [2.7307267]
 [2.794842 ]
 [2.7262056]
 [2.7077324]]
[-4.93155771 -1.87411844]
106.87211058751963



  5%|▌         | 5037/100000 [00:13<04:11, 377.05it/s]

[[ 2.64441454 -1.25270409]
 [ 1.37313988  2.12282958]
 [ 1.19447058  2.0911298 ]
 [ 3.27631106 -2.90879862]
 [ 4.62742269 -3.60680926]
 [ 4.87226423  3.7406957 ]
 [ 1.4107165   2.59943343]
 [-2.18509862 -1.72685583]
 [ 2.39967781 -3.69962483]
 [ 4.7889394  -0.26646447]]
[[3.230699 ]
 [3.1536107]
 [3.1528974]
 [3.2691238]
 [3.283615 ]
 [3.0985322]
 [3.1427422]
 [3.1989737]
 [3.2812824]
 [3.2023025]]
[4.87226423 3.7406957 ]
124.80491387922596



  6%|▌         | 6012/100000 [00:19<05:02, 310.58it/s]

[[-3.76638844  0.3024628 ]
 [ 1.83257495 -3.85706322]
 [ 4.80712243 -1.30860061]
 [ 0.69804863  2.69315219]
 [-3.0773104   2.2618069 ]
 [ 2.3280455   0.40487736]
 [-0.07214833 -3.96350471]
 [-2.05689779 -1.2813559 ]
 [ 3.97579624  0.55996681]
 [ 2.50609122 -2.83226201]]
[[4.2863817]
 [4.2458353]
 [4.1381154]
 [4.1314583]
 [4.2217712]
 [4.146182 ]
 [4.286223 ]
 [4.27389  ]
 [4.115294 ]
 [4.2107697]]
[3.97579624 0.55996681]
96.28798931686569



  7%|▋         | 7019/100000 [00:26<05:50, 265.50it/s]

[[ 1.19301421 -4.68181737]
 [-3.42138932  0.56898022]
 [ 1.11914123 -1.56001737]
 [ 3.22136206 -1.73557403]
 [-1.9207443   3.60857945]
 [ 1.02189925  0.62953495]
 [-4.45552344 -0.0324526 ]
 [-3.29929684  0.75585145]
 [ 2.29149174 -0.2282083 ]
 [ 2.5172217   0.20405049]]
[[4.1190333]
 [4.079747 ]
 [4.0552607]
 [4.024284 ]
 [3.994761 ]
 [4.0088744]
 [4.1083155]
 [4.073927 ]
 [4.0059085]
 [3.9924517]]
[2.5172217  0.20405049]
86.45951969817233



  8%|▊         | 8018/100000 [00:33<06:29, 235.85it/s]

[[ 4.60971856  1.24592207]
 [ 4.31727787  1.40220692]
 [ 3.99563149  3.28081167]
 [ 2.76718135 -1.38174774]
 [-4.07271725  2.03037463]
 [-2.03836999  2.86645779]
 [ 3.207453   -0.04179146]
 [-1.63453869  3.09006431]
 [-2.29150106  0.55010561]
 [ 1.70937213  2.4145253 ]]
[[2.613011 ]
 [2.6097195]
 [2.5782473]
 [2.6512148]
 [2.5842056]
 [2.5728536]
 [2.6304674]
 [2.569808 ]
 [2.6072187]
 [2.5865836]]
[-1.63453869  3.09006431]
101.07790378438366



  9%|▉         | 9020/100000 [00:42<07:10, 211.15it/s]

[[-3.20007207  3.06783917]
 [ 4.38732013 -1.38603807]
 [ 0.06971521 -1.13122268]
 [-2.82994959  3.62628694]
 [ 2.15050753 -3.50355391]
 [ 1.11438235 -3.97248967]
 [-1.59337059 -3.24335302]
 [ 3.07087102  4.49481594]
 [-1.72823904 -2.25755632]
 [ 1.92416357 -1.63622588]]
[[3.2365577]
 [3.2902122]
 [3.2832415]
 [3.2320986]
 [3.309979 ]
 [3.3179684]
 [3.3075802]
 [3.2123506]
 [3.2947488]
 [3.293676 ]]
[3.07087102 4.49481594]
119.36228702762989



 10%|█         | 10015/100000 [00:52<07:50, 191.19it/s]

[[ 4.9490684  -2.90464795]
 [-2.31923732  4.02253474]
 [ 3.91730115 -3.61736207]
 [ 3.32590589 -1.4657341 ]
 [-2.96345622 -3.8429181 ]
 [-4.84972647  1.01144892]
 [ 1.62834149 -2.1642228 ]
 [ 3.73341054 -1.50259549]
 [-0.15130393 -0.70831609]
 [-4.03993541  1.94781591]]
[[4.256851 ]
 [4.227716 ]
 [4.288028 ]
 [4.2556543]
 [4.4242268]
 [4.3693285]
 [4.297648 ]
 [4.249589 ]
 [4.3028827]
 [4.323264 ]]
[-2.31923732  4.02253474]
112.92088434260299



 11%|█         | 11014/100000 [01:03<08:30, 174.25it/s]

[[ 3.15291082 -0.30633336]
 [-1.25142101 -4.99005238]
 [ 1.50225009 -3.14367997]
 [-1.02180565 -2.46263784]
 [ 0.75807252 -3.71360557]
 [-0.82958358 -3.54967909]
 [ 2.02899824  3.87648714]
 [-2.60406282 -3.56768352]
 [-1.52933465  0.58915512]
 [ 0.53981045  1.98454959]]
[[2.5151997]
 [2.5690753]
 [2.5556383]
 [2.5318053]
 [2.5603514]
 [2.5493865]
 [2.4394126]
 [2.5401995]
 [2.482655 ]
 [2.466352 ]]
[2.02899824 3.87648714]
107.96885962416408



 11%|█▏        | 11314/100000 [01:06<08:42, 169.62it/s]

KeyboardInterrupt: 

 11%|█▏        | 11314/100000 [01:20<10:27, 141.39it/s]